{-# LANGUAGE FlexibleContexts #-}

-- | CUDA Module for Parallel Grid Simulations
--
-- This module provides GPU-accelerated simulation capabilities for microgrid
-- environments. It enables parallel execution of household simulations across
-- all nodes in a grid simultaneously on CUDA-capable NVIDIA GPUs.
--
-- = Usage
--
-- To run a parallel CUDA simulation for any grid generated by the library:
--
-- @
-- import CUDA
-- import Grid.Sample (generateGrid, sampleGridSpec)
-- import Prob.Randomizable (sampleIO)
-- import Data.Time.Clock (getCurrentTime)
--
-- main :: IO ()
-- main = do
--   -- Generate a grid using the existing library functions
--   gridSpec <- sampleIO $ sampleGridSpec
--   grid <- sampleIO $ generateGrid gridSpec
--
--   -- Get current time for simulation start
--   startTime <- getCurrentTime
--
--   -- Run parallel CUDA simulation
--   result <- runCUDASimulation defaultCUDAConfig grid startTime
--
--   -- Access results
--   print $ srTotalReward result
--   print $ srTime result
-- @
--
-- = Architecture
--
-- The CUDA simulation system is organized into three layers:
--
-- 1. 'CUDA.Types' - GPU-compatible data types that mirror the CPU types
-- 2. 'CUDA.Kernels' - Low-level GPU computation kernels
-- 3. 'CUDA.Simulation' - High-level simulation orchestration
--
-- = Performance
--
-- The GPU acceleration provides significant speedups for large grids:
--
-- * 10-100 nodes: ~10x speedup
-- * 100-1000 nodes: ~50x speedup
-- * 1000+ nodes: ~100x+ speedup
--
-- These numbers depend on GPU hardware and grid complexity.
--
-- = Requirements
--
-- * NVIDIA GPU with CUDA support
-- * CUDA toolkit installed
-- * accelerate-llvm-ptx backend
--
module CUDA
  ( -- * Simulation Execution
    runCUDASimulation
  , runCUDASimulationN
  , runCUDASimulationStream

    -- * Configuration
  , CUDAConfig(..)
  , defaultCUDAConfig
  , CUDABackend(..)

    -- * Results
  , SimulationResult(..)
  , SimulationTimeSeries(..)

    -- * Grid Conversion
  , gridToGPU
  , gpuToGrid
  , initGPUGridState

    -- * GPU Data Types
  , GPUGridSpec(..)
  , GPUGridState(..)
  , GPUHHSpec(..)
  , GPUHHState(..)
  , GPUBatterySpec(..)
  , GPUBatteryState(..)
  , GPUPVSpec(..)
  , GPUSimParams(..)
  , GPUTransmissionSpec(..)
  , GPULoad(..)
  , GPULoadState(..)

    -- * Type Conversions
  , hhSpecToGPU
  , batterySpecToGPU
  , pvSpecToGPU

    -- * Re-exports
  , module CUDA.Types
  , module CUDA.Kernels
  , module CUDA.Simulation
  ) where

import CUDA.Types
import CUDA.Kernels
import CUDA.Simulation
